---
title: "C. Weber Resume"
author: "C. Weber"
format: html
editor: visual
---

## Candice Louise Weber

8156 Varina Road<br>
Richmond, VA 23231<br>
804-298-4451<br>
candiceweber7@gmail.com<br>


## Education

M.A., Art History, University of Illinois - Chicago, 2009<br>
B.A., Art History, Webster University, 2005

## Professional Experience
**Virginia Commonwealth University, Richmond, VA**<br>
October 2023-Present Senior Research Administrator and Reporting Manager, School of Medicine<br>
2022-2023	Director of Training and Compliance, School of Medicine<br>
2016-2022	Associate Director for Research Administration, School of Medicine<br>
2013-2016	Senior Research Administrator, School of Medicine<br>
2012-2013	Research Administrator, School of Medicine<br>

**Northwestern University, Evanston, IL**<br>
2010-2012	Research Administrator, College of Arts and Sciences<br>
2009-2010	Graduate Program Coordinator, College of Arts and Sciences<br>
2007-2009	Graduate Program Assistant, Department of Philosophy<br>
